### ISSUE TITLE
Implement AlephiumClient for Blockchain Data Fetching

### ISSUE THREAD

**Issue by raduciobanu22** [ThinEdgeLabs/bento-alephium#1]
**Objective**
Create a robust and reusable Rust client for interacting with Alephium nodes, providing a foundation for the indexer to fetch and process blockchain data efficiently.

**Scope of Work**
1. HTTP Client Implementation
- Implement async HTTP client using reqwest/hyper
- Create typed responses for Alephium API endpoints
- Add proper error handling and retry mechanisms
- Implement connection pooling and timeout management

2. Blockchain Data Types
- Create Rust types for blocks, transactions, and events
- Implement serialization/deserialization using serde
- Add validation for blockchain data structures
- Create helper methods for data conversion

3. Node Communication
- Implement WebSocket subscription for new blocks
- Add methods for fetching historical blocks
- Create batch processing capabilities
- Implement rate limiting and backoff strategies

**Requirements**
- Code should be async-first and properly handle concurrency
- Comprehensive error handling with custom error types
- Complete test suite with mocked responses
- Documentation for all public interfaces
- Configuration through environment variables

**Comment by TropicalDog17** [comment]
May I work on this @raduciobanu22?

**Comment by htiennv** [comment]
Hi, can i take this issue. I have strong coding skill in Rust. Thanks @raduciobanu22

**Comment by tnv1** [comment]
Hi, Can I take this issue? Thanks

**Comment by raduciobanu22** [comment]
> May I work on this @raduciobanu22?

Assigned!

**Comment by mimisavage** [comment]
I’d like to resolve this.

**Comment by Supa-mega** [comment]
I'd like to handle this task.

**Comment by raduciobanu22** [comment]
@TropicalDog17 Would be great if you could create a quick PR with the initial project skeleton so that everyone else working on the other issues can use it.
