### ISSUE TITLE
Implement Database Layer with Diesel and PostgreSQL

### ISSUE THREAD

**Issue by raduciobanu22** [ThinEdgeLabs/bento-alephium#2]
**Objective**
Create a robust database layer using Diesel ORM and PostgreSQL to store and manage indexed blockchain data efficiently, ensuring data consistency and quick querying capabilities.

**Scope of Work**
1. Schema Design
- Define tables for blocks, transactions, and events
- Create necessary migrations using Diesel
- Implement indexes for optimal query performance
- Design schema to support future extensions

2. Model Implementation
- Create Diesel models for all entities
- Implement relationships between models
- Add validation and conversion methods
- Create helper methods for common queries

3. Connection Management
- Implement connection pooling
- Add transaction management
- Implement proper error handling

**Requirements**
- Properly managed database migrations
- Optimized schema design for typical queries
- Complete test suite with test database

**Comment by TropicalDog17** [comment]
May I work on this issue, I have experience in Rust and have contributed to various Rust repos. @raduciobanu22

**Comment by khayss** [comment]
Could I grab this task?

I am a backend developer and I can build backends using Rust and NodeJS. I believe I have the knowledge and skill to work on this issue.

**Comment by tnv1** [comment]
Hi, Can I take this issue? Thanks

**Comment by abdegenius** [comment]
Can I start working on this?

**Comment by Supa-mega** [comment]
I'd like to handle this task.

**Comment by GideonBature** [comment]
May I try my hand at this?

My name is Gideon Bature, a Software Engineer, I have experience working with Rust (Actix-web) and the DieselORM with PostgreSQL database. I even build a RESTful API backend web application project with these exact technology last two months. I will send my first PR within 72 hours.

Thank you!

**Comment by JuanPabloRodriguezC** [comment]
I'd love to give this a go. I have experience with PostgreSQL and admittedly not much with rust but I am willing to learn on the go using the Diesel documentation which will be easy since I already have PostgreSQL up and running on my machine.

**Comment by oluchicharity** [comment]
I'm Oluchi, a backend and smart contract developer passionate about building scalable and well-architected systems. I focus on database design, API development, and ensuring seamless integration of backend services. i would love to get a go on this issue.

**Comment by BrunoAmbricca** [comment]
I would like to work on this issue

**Comment by ShantelPeters** [comment]
Can I work on this, please?

**Comment by Jagadeeshftw** [comment]
I’d love to work on this issue as I have strong experience in building and managing APIs, handling server-side operations, and ensuring robust back-end performance.
Please assign this to me, and I’ll deliver a secure and high-quality PR within 12-24 hours.

**Comment by suhas-sensei** [comment]
Can I contribute to this one? i have experience in postgreSQL and have worked on similiar projects in previous odhacks, so would love to contribute.

**Comment by DuendexCR** [comment]
Can I tackle this one?

**Comment by raduciobanu22** [comment]
> Hi @raduciobanu22 , can i take this issue?. I have strong coding skill in Rust! Thanks

@htiennv Assigned to you!
Either you or @TropicalDog17 please create a first PR with the Rust project skeleton, like the Cargo files, etc.

**Comment by raduciobanu22** [comment]
> Thanks @raduciobanu22 , i will create a quickly PR for initial project. Is it ok if I following this exists project:
> 
> https://github.com/ThinEdgeLabs/bento
> 
> cc @TropicalDog17

Yes that's ok.

**Comment by raduciobanu22** [comment]
@TropicalDog17 @htiennv Looking pretty good so far, keep it up!

**Comment by htiennv** [comment]
@raduciobanu22 yeah, if you see anything that needs improvement please let us know. Thanks
